### ISSUE TITLE
Discrepancy between relative frequency from Smurf(No of Articles(%)) and relative frequency based on numbers from the labs-API 

### ISSUE THREAD

**Issue by maxodsbjerg** [kb-dk/kb-labs-api#16]
See the following smurf on "revolution": 
http://labs.statsbiblioteket.dk/smurf?q=revolution
When observing the great year of revolutions, 1848, we see a relative frequency of 

0.588937 (943/160119 articles) 

When calculating the same frequency with numbers from the API we get the following: 

(943/137754)*100 = 0.6845536

Why are there more articles when we ask Smurf?

**Comment by tokee** [comment]
Smurf uses the query `*:*` for normalising. This is problematic as the backing index contains both articles (hundreds of millions), pages (tens of millions) and newspapers(below 100). The page-documents are never matched in a text-based query as they do not contain any text, only metadata about the specific page. But they are matched with the `*:*`-query. Depending on optics, Smurf is the problem here as it should restrict both the user issues query and the normalising query to articles. The labsapi does this.

Nevertheless this is quite confusing from the outside, so this should be addressed explicitly in issue #15.
